Update build-snapcraft.yml

diff --git a/.github/workflows/build-snapcraft.yml b/.github/workflows/build-snapcraft.yml
--- a/.github/workflows/build-snapcraft.yml
+++ b/.github/workflows/build-snapcraft.yml
@@ -9,30 +9,39 @@ on:
 jobs:
   build-snapcraft:
     runs-on: ubuntu-24.04
-    steps:
-    - uses: actions/checkout@v4
 
-    - name: Install packages
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
+
+    - name: Install required packages
       run: |
+        sudo apt update
         sudo apt install -y gcc xorg-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa wget snapd
-        sudo snap refresh
         sudo snap install snapcraft --classic
         sudo snap install multipass
 
     - name: Copy Snapcraft files to source
       run: |
-        mv dist/snapcraft/* src
+        cp -r dist/snapcraft/* src/
 
-    - name: List src
+    - name: Fix permissions
+      run: |
+        chmod -R a+rX src
+
+    - name: List contents of src
       run: |
         ls -l src
+        ls -l src/snapcraft.yaml || echo "snapcraft.yaml not found"
 
-    - name: Build Snapcraft
+    - name: Build Snapcraft using multipass
       run: |
         cd src
-        sudo env SNAPCRAFT_BUILD_ENVIRONMENT=multipass snapcraft
+        snapcraft
+      env:
+        SNAPCRAFT_BUILD_ENVIRONMENT: multipass
 
-    - name: Upload artifacts
+    - name: Upload .snap artifacts
       uses: actions/upload-artifact@v4
       with:
         name: build-snapcraft
